rm(list = ls())
library(lubridate)
Datos <- read.table(file = "household_power_consumption.txt" , header = TRUE, sep = ";")
Datos$Fecha <- dmy_hms(paste(Datos$Date, Datos$Time, sep = " "))
SubConjunto <- subset(x = Datos, subset = Datos$Fecha >= dmy_hms("01/02/2007 00:00:00") & Datos$Fecha <= dmy_hms("02/02/2007 23:59:59"))
SubConjunto$Global_active_power <- as.numeric(as.character(SubConjunto$Global_active_power))
SubConjunto$Sub_metering_1 <- as.numeric(as.character(SubConjunto$Sub_metering_1))
SubConjunto$Sub_metering_2 <- as.numeric(as.character(SubConjunto$Sub_metering_2))
SubConjunto$Sub_metering_3 <- as.numeric(as.character(SubConjunto$Sub_metering_3))
SubConjunto$Voltage <- as.numeric(as.character(SubConjunto$Voltage))
SubConjunto$Global_reactive_power <- as.numeric(as.character(SubConjunto$Global_reactive_power))

#Plot 3
png(filename = "./Plot3.png", width = 480, height = 480, bg = "transparent")
par(col="black", new=FALSE)
plot(x = SubConjunto$Fecha, y = SubConjunto$Sub_metering_1, type = "s", main = "", xlab = "", ylab = "", ylim = c(0,40),  axes = TRUE)
par(col="red", new=TRUE)
plot(x = SubConjunto$Fecha, y = SubConjunto$Sub_metering_2, type = "s", main = "", xlab = "", ylab = "", ylim = c(0,40), axes = FALSE)
par(col="blue", new=TRUE)
plot(x = SubConjunto$Fecha, y = SubConjunto$Sub_metering_3, type = "s", main = "", xlab = "", ylab = "Energy Sub Metering", ylim = c(0,40), axes = FALSE)
par(new=FALSE)
legend('topright', c(names(SubConjunto)[7],names(SubConjunto)[8],names(SubConjunto)[9]),lty=1, col=c('Black', 'Red', 'Blue'), bty='o', cex=.75, border = 'Black', box.col = 'Black')
dev.off()